/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snakesandladders_client;

/**
 *
 * @author Ozen
 */
public class FrmClient extends javax.swing.JFrame {
    
    public static FrmClient frmClient;
    
    /**
     * Creates new form FrmClient
     */
    static int currentPosition = 0;
    public FrmClient() {
        initComponents();
        frmClient = this;
        int endPosition = 100;
        
    }
        public static int zarAt(){
            int rand = (int)(Math.random() * 6) + 1;
            frmClient.lbl_ZarDegeri.setText(Integer.toString(rand));
            return rand;
    }
    
    
    public static int tur(int totalPoint){
        int returnPoint = totalPoint;       // gelen puan
        returnPoint = zarAt();              // zar puanı
        if (returnPoint+totalPoint<=100)
            returnPoint+=totalPoint;        // zar + gelen puan
        if (returnPoint == 100){             // oyuncu1 kazandı
            Message msg = new Message(Message.Message_Type.Bitis);      
            Client.SendMessage(msg);                                    
        }
        
        //Ladders
        if(returnPoint == 1)
            returnPoint = 38;
        else if(returnPoint == 4)
            returnPoint = 14;
        else if(returnPoint == 8)
            returnPoint = 30;
        else if(returnPoint == 21)
            returnPoint = 42;
        else if(returnPoint == 28)
            returnPoint = 76;
        else if(returnPoint == 50)
            returnPoint = 67;
        else if(returnPoint == 71)
            returnPoint = 92;
        else if(returnPoint == 80)
            returnPoint = 99;
        
        //Snakes
        else if(returnPoint == 97)
            returnPoint = 78;
        else if(returnPoint == 95)
            returnPoint = 56;
        else if(returnPoint == 88)
            returnPoint = 24;
        else if(returnPoint == 62)
            returnPoint = 18;
        else if(returnPoint == 48)
            returnPoint = 26;
        else if(returnPoint == 36)
            returnPoint = 6;
        else if(returnPoint == 32)
            returnPoint = 10;
        
        
            
        return returnPoint;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_Oyuncu_1 = new javax.swing.JLabel();
        lbl_Oyuncu_2 = new javax.swing.JLabel();
        btn_ZarAt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbl_ZarDegeri = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_Oyuncu_2_Pozisyon = new javax.swing.JLabel();
        lbl_Oyuncu_1_Pozisyon = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        btn_GirisYap = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_ip = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Oyuncu 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("Oyuncu 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, -1, -1));

        lbl_Oyuncu_1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_Oyuncu_1.setText("NULL");
        getContentPane().add(lbl_Oyuncu_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        lbl_Oyuncu_2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_Oyuncu_2.setText("NULL");
        getContentPane().add(lbl_Oyuncu_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, -1, -1));

        btn_ZarAt.setText("Zar At");
        btn_ZarAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ZarAtActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ZarAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 620, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setText("Zar Değeri");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, -1, -1));

        lbl_ZarDegeri.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_ZarDegeri.setText("0");
        getContentPane().add(lbl_ZarDegeri, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Pozisyon");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("Pozisyon");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, -1, -1));

        lbl_Oyuncu_2_Pozisyon.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_Oyuncu_2_Pozisyon.setText("0");
        getContentPane().add(lbl_Oyuncu_2_Pozisyon, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, -1, -1));

        lbl_Oyuncu_1_Pozisyon.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_Oyuncu_1_Pozisyon.setText("0");
        getContentPane().add(lbl_Oyuncu_1_Pozisyon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        txt_name.setText("Ad Giriniz...");
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 130, -1));

        btn_GirisYap.setText("Giriş Yap");
        btn_GirisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GirisYapActionPerformed(evt);
            }
        });
        getContentPane().add(btn_GirisYap, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snakesandladders_client/SnakesAndLaddersMasa.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 490, 480));

        txt_ip.setText("127.0.0.1");
        getContentPane().add(txt_ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 20, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GirisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GirisYapActionPerformed
        // TODO add your handling code here:
        Client myClient = new Client();
        String ip = txt_ip.getText(); 
        myClient.Start(ip, 5000);
        btn_GirisYap.setEnabled(false);
        txt_name.setEnabled(false);
        txt_ip.setEnabled(false);
        btn_ZarAt.setEnabled(false);
        
    }//GEN-LAST:event_btn_GirisYapActionPerformed

    private void btn_ZarAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ZarAtActionPerformed
        currentPosition = tur(currentPosition);                                     // zar atılıp yeni değer döndürülür.
        lbl_Oyuncu_1.setText(Integer.toString(currentPosition));                    // 
    }//GEN-LAST:event_btn_ZarAtActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        
    }//GEN-LAST:event_txt_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GirisYap;
    private javax.swing.JButton btn_ZarAt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_Oyuncu_1;
    private javax.swing.JLabel lbl_Oyuncu_1_Pozisyon;
    private javax.swing.JLabel lbl_Oyuncu_2;
    private javax.swing.JLabel lbl_Oyuncu_2_Pozisyon;
    private javax.swing.JLabel lbl_ZarDegeri;
    private javax.swing.JTextField txt_ip;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
